=== nlubczynski/SchoolWork/3316A/Assignment 2/Schema.xsd
<?xml version="1.0" encoding="utf-8"?>
<schema elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema">
  <element name="root">
    <complexType>
      <sequence>
        <element minOccurs="0" maxOccurs="unbounded" name="band">
          <complexType>
            <sequence>
              <element maxOccurs="unbounded" minOccurs="1" name="member">
                <complexType>
                  <attribute name="name" type="string" use="required" />
                  <attribute name="instrument" type="string" use="required" />
                </complexType>
              </element>
              <element name="album" minOccurs="1" maxOccurs="unbounded">
                <complexType>
                  <sequence>
                    <element maxOccurs="unbounded" minOccurs="1" name="song">
                      <complexType>
                        <all>
                          <element default="Track1" name="name" type="string" minOccurs="1" maxOccurs="1" />
                          <element name="trackLength" type="duration" minOccurs="1" maxOccurs="1" />
                        </all>
                      </complexType>
                    </element>
                    <element minOccurs="0" maxOccurs="unbounded" name="reviewer">
                      <complexType>
                        <simpleContent>
                          <extension base="string">
                            <attribute name="ref" type="IDREF" use="required" />
                          </extension>
                        </simpleContent>
                      </complexType>
                    </element>
                  </sequence>
                  <attribute name="name" type="string" use="required" />
                </complexType>
              </element>
              <element minOccurs="0" maxOccurs="unbounded" name="show">
                  <complexType>
                    <sequence maxOccurs="unbounded">
                        <element name="date" type="date" minOccurs="1" maxOccurs="1" />
                        <element name="venue" type="string" minOccurs="1" maxOccurs="1" />
                    </sequence>
                  </complexType>
              </element>
            </sequence>
            <attribute name="name" type="string" use="required" />
            <attribute name="size" type="positiveInteger" use="optional" default="1" />
          </complexType>
        </element>
        <element minOccurs="0" maxOccurs="unbounded" name="reviewer">
            <complexType>
              <all>
                <element minOccurs="1" maxOccurs="1" name="name" type="NCName" />
                <element minOccurs="0" maxOccurs="1" name="company" type="string" />
              </all>
              <attribute name="id" type="ID" use="required" />
            </complexType>
        </element>
      </sequence>
    </complexType>
    <unique name="idAndName">
      <selector xpath="reviewer"/>
      <field    xpath="name"/>
    </unique>
  </element>
</schema>

=== nlubczynski/SchoolWork/3316A/Assignment 2/WebTechAssignment2.xml
<?xml version="1.0" encoding="utf-8"?>
<root xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" 
      xs:noNamespaceSchemaLocation="Schema.xsd">
  <band name="MyBand" size="2">
    <member name="John Doe" instrument="Voice" />
    <member name="Jane Smith" instrument="Piano" />
    <album name="Album1">
      <song>
        <name>Track1</name>
        <trackLength>PT1M20S</trackLength>
      </song>
      <song>
        <name>Track2</name>
        <trackLength>PT3M45S</trackLength>
      </song>
      <reviewer ref="PressID1">This album was awesome</reviewer>
    </album>
    <show>
      <date>2014-01-23</date>
      <venue>Air Canada Center</venue>
      <date>2014-02-14</date>
      <venue>Molson Amplitheater</venue>
    </show>
  </band>
  <band name="YourBand" size="1">
    <member name="Joe Smith" instrument="Guitar"/>
    <album name="MyFirstAlbum">
      <song>
        <name>A great song</name>
        <trackLength>PT5M32S</trackLength>
      </song>
      <reviewer ref="PressID2">This album is not very good</reviewer>
    </album>
  </band>
  <reviewer id="PressID1">
    <name>Name1</name>
  </reviewer>
  <reviewer id="PressID2">
    <name>Name2</name>
    <company>New York Times</company>
  </reviewer>
  <reviewer id="PressID3">
    <name>Name3</name>
    <company>New York Times</company>
  </reviewer>
</root>
